services:
  - type: web
    name: frontend
    env: node
    buildCommand: pnpm install && pnpm exec nx build frontend
    startCommand: npx serve dist/apps/frontend
    staticPublishPath: dist/apps/frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SERVER_API_URL
        value: https://web-object-renderer-backend.onrender.com # Backend URL on Render

  - type: web
    name: backend
    env: node
    buildCommand: pnpm install && pnpm exec nx build backend
    startCommand: npx serve dist/apps/backend
    envVars:
      - key: BACKEND_SERVER_PORT
        value: 10000 # Render automatically sets the PORT environment variable
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
