version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.8

jobs:
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install dependencies
          command: pnpm install
      - save_cache:
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

  test:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install dev tools (to get nx etc.)
          command: pnpm install --ignore-scripts
      - run:
          name: Install necessary libraries
          command: sudo apt-get update && sudo apt-get install -y libepoxy0 libvpx7 libevent-2.1-7 libopus0 libfontconfig1 libfreetype6 libwebpmux3 libharfbuzz0b libjpeg8 libpng16-16 libgtk-4-1 libpangocairo-1.0-0 libpango-1.0-0 libgdk-pixbuf-2.0-0 libcairo-gobject2 libcairo2 libgraphene-1.0-0 libxslt1.1 liblcms2-2 libwoff2dec1 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 libgstaudio1.0-0 libgstvideo1.0-0 libgstaudio1.0-0
      - run:
          name: Install Playwright Browsers
          command: pnpm exec playwright install
      - run:
          name: Run Playwright E2E tests
          command: pnpm exec nx run frontend-e2e:e2e
      - store_artifacts:
          path: playwright-report
          destination: playwright-report

  deploy-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build frontend
          command: pnpm exec nx build frontend
      - run:
          name: Deploy frontend to Render
          command: curl -X POST https://api.render.com/deploy/srv-cvm0khm3jp1c738rqgm0?key=l3rweXFRhI4

  deploy-backend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build backend
          command: pnpm exec nx build backend
      - run:
          name: Deploy backend to Render
          command: curl -X POST https://api.render.com/deploy/srv-cvm56d3e5dus73afgv1g?key=tqkNKomp9x0

workflows:
  version: 2
  ci-cd:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy-frontend:
          requires:
            - test
          filters:
            branches:
              only: main
      - deploy-backend:
          requires:
            - test
          filters:
            branches:
              only: main
